-- 退货申请表
CREATE TABLE `seckill_refund` (
  `id` bigint NOT NULL COMMENT '退货ID',
  `refund_no` varchar(64) NOT NULL COMMENT '退货流水号',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `order_code` varchar(30) NOT NULL COMMENT '订单编码',
  `payment_id` bigint DEFAULT NULL COMMENT '支付ID',
  `payment_no` varchar(64) DEFAULT NULL COMMENT '支付流水号',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `user_name` varchar(30) NOT NULL COMMENT '用户名称',
  `refund_amount` decimal(10,3) NOT NULL COMMENT '退货金额',
  `refund_reason` varchar(200) NOT NULL COMMENT '退货原因',
  `refund_type` tinyint NOT NULL DEFAULT '1' COMMENT '退货类型 1:仅退款 2:退货退款',
  `refund_status` tinyint NOT NULL DEFAULT '1' COMMENT '退货状态 1:申请中 2:审核通过 3:审核拒绝 4:退款中 5:退款成功 6:退款失败 7:已完成',
  `apply_time` datetime(3) NOT NULL COMMENT '申请时间',
  `audit_time` datetime(3) DEFAULT NULL COMMENT '审核时间',
  `audit_user_id` bigint DEFAULT NULL COMMENT '审核人ID',
  `audit_user_name` varchar(30) DEFAULT NULL COMMENT '审核人名称',
  `audit_remark` varchar(200) DEFAULT NULL COMMENT '审核备注',
  `refund_time` datetime(3) DEFAULT NULL COMMENT '退款时间',
  `third_party_refund_no` varchar(64) DEFAULT NULL COMMENT '第三方退款流水号',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  `create_user_id` bigint NOT NULL COMMENT '创建人ID',
  `create_user_name` varchar(30) NOT NULL COMMENT '创建人名称',
  `create_time` datetime(3) NOT NULL COMMENT '创建时间',
  `update_user_id` bigint DEFAULT NULL COMMENT '修改人ID',
  `update_user_name` varchar(30) DEFAULT NULL COMMENT '修改人名称',
  `update_time` datetime(3) DEFAULT NULL COMMENT '修改时间',
  `is_del` tinyint(1) DEFAULT '0' COMMENT '是否删除 1:已删除 0:未删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_refund_no` (`refund_no`) USING BTREE,
  KEY `idx_order_id` (`order_id`) USING BTREE,
  KEY `idx_payment_id` (`payment_id`) USING BTREE,
  KEY `idx_user_id` (`user_id`) USING BTREE,
  KEY `idx_refund_status` (`refund_status`) USING BTREE,
  KEY `idx_create_time` (`create_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='秒杀退货申请表';

-- 退货日志表
CREATE TABLE `seckill_refund_log` (
  `id` bigint NOT NULL COMMENT 'ID',
  `refund_id` bigint NOT NULL COMMENT '退货ID',
  `refund_no` varchar(64) NOT NULL COMMENT '退货流水号',
  `operation_type` tinyint NOT NULL COMMENT '操作类型 1:申请退货 2:审核通过 3:审核拒绝 4:退款成功 5:退款失败 6:完成退货',
  `operation_desc` varchar(200) NOT NULL COMMENT '操作描述',
  `operator_id` bigint NOT NULL COMMENT '操作人ID',
  `operator_name` varchar(30) NOT NULL COMMENT '操作人名称',
  `request_data` text COMMENT '请求数据',
  `response_data` text COMMENT '响应数据',
  `create_time` datetime(3) NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_refund_id` (`refund_id`) USING BTREE,
  KEY `idx_refund_no` (`refund_no`) USING BTREE,
  KEY `idx_create_time` (`create_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='退货日志表';